server:
  port: 8080
  servlet:
    context-path: /bookstore

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/bookstore_mysql"
    username: "root"
    password: "1234"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

cloudinary:
  cloud-name: dfrnamjn6
  api-key: 878388764129245
  api-secret: IrSHvueEzLJQGnWRDoTnKquoqDE
